name : Demo MMDT 141
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  demo-mmdt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: "pip"
      - name: Install libraries
        run: pip install -r requirements.txt
      - name: Print Weather API Key
        run: echo ${{ secrets.WEATHER_API_KEY }}
      - name: Run Python main file
        run: python main.py
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}